name: Linux Build

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgphoto2-dev \
            libavformat-dev \
            libavcodec-dev \
            libavutil-dev \
            libswscale-dev \
            libkmod-dev

      - name: Build project
        run: make
